modify to support flash image dtb dtbo
supported devices: a73xq m52xq a52xq

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -300,14 +300,14 @@ do_devicecheck() {
   for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "- OK ! ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "! Unsupported device, this device is $devicename. Aborting... !";
   fi;
 }
 int2ver() {
@@ -322,7 +322,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
+  ui_print "- Checking Android version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -341,9 +341,11 @@ do_versioncheck() {
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+    ui_print "- Current Android version: $android_ver is supported.";
+    ui_print " ";
+    ui_print "Continuing with flashing process...";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    abort "- Currently Android $android_ver is unsupported. This kernel is only for Android $supported_ver. Aborting... !";
   fi;
 }
 do_levelcheck() {
@@ -364,9 +366,9 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | sort -g | grep -n "$parsed_lvl" | grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+    ui_print ">> $android_lvl <<";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "! Unsupported Android security patch level. Aborting... !";
   fi;
 }
 do_vendorlevelcheck() {
@@ -420,10 +422,10 @@ do_modules() {
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     if [ ! -d /data/adb -o ! -d /data/data/android ]; then
       ui_print " " "Warning: No /data access for kernel helper systemless module!";
-      return 1;
+    else
+      ui_print " " "Creating kernel helper systemless module...";
+      cd $AKHOME/modules;
     fi;
-    cd $AKHOME/modules;
-    ui_print " " "Creating kernel helper systemless module...";
     if [ -d /data/adb/magisk -a -f $AKHOME/magisk_patched ] || [ -d /data/data/me.weishu.kernelsu -a -f $AKHOME/kernelsu_patched ]; then
       umask=$(umask);
       moddir=/data/adb/modules/ak3-helper;
@@ -469,57 +471,59 @@ do_modules() {
       umask $umask;
       /system/bin/chcon -hR "u:object_r:system_file:s0" $moddir;
       [ "$umountksu" ] && umount /data/adb/modules_update;
+      return 0;
     else
-      ui_print "Magisk/KernelSU installation not found. Skipped!";
+      ui_print "- Magisk/KernelSU installation not found";
     fi;
-  else
-    cd $AKHOME/modules;
-    ui_print " " "Pushing modules...";
-    if [ -d /dev/block/mapper ]; then
-      for block in system vendor product; do
-        for slot in "" _a _b; do
-          blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null;
-        done;
+  fi
+
+  cd $AKHOME/modules;
+  ui_print " " "- Pushing modules...";
+  if [ -d /dev/block/mapper ]; then
+    for block in system vendor product; do
+      for slot in "" _a _b; do
+        blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null;
       done;
-    fi;
-    if [ ! -d /postinstall/tmp ]; then
-      for mount in /system /vendor /product; do
-        if is_mounted $mount; then
-          mount -o rw,remount -t auto $mount && echo "$mount (rw)" >&2;
-        fi;
-      done;
-    fi;
-    for module in $(find . -name '*.ko'); do
-      modtarget=$POSTINSTALL$(echo $module | cut -c2-);
-      if [ ! -e $modtarget ]; then
-        case $module in
-          */vendor/*) modcon=vendor;;
-          */product/*) modcon=product;;
-          *) modcon=system;;
-        esac;
-      fi;
-      if is_mounted $modtarget; then
-        mount -o rw,remount -t auto $modtarget && echo "$modtarget (rw)" >&2;
-      fi;
-      mkdir -p $(dirname $modtarget);
-      cp -rLf $module $modtarget;
-      chown 0:0 $modtarget;
-      chmod 644 $modtarget;
-      if [ "$modcon" ]; then
-        /system/bin/chcon "u:object_r:${modcon}_file:s0" $modtarget;
-      fi;
-      if is_mounted $modtarget; then
-        mount -o ro,remount -t auto $modtarget && echo "$modtarget (ro)" >&2;
+    done;
+  fi;
+  if [ ! -d /postinstall/tmp ]; then
+    for mount in /system /vendor /product; do
+      if is_mounted $mount; then
+        mount -o rw,remount -t auto $mount && echo "$mount (rw)" >&2;
       fi;
     done;
-    if [ ! -d /postinstall/tmp ]; then
-      for mount in /system /vendor /product; do
-        if is_mounted $mount; then
-          mount -o ro,remount -t auto $mount && echo "$mount (ro)" >&2;
-        fi;
-      done;
-    fi;
   fi;
+  for module in $(find . -type f); do
+    modtarget=$POSTINSTALL$(echo $module | cut -c2-);
+    if [ ! -e $modtarget ]; then
+      case $module in
+        */vendor/*) modcon=vendor;;
+        */product/*) modcon=product;;
+        *) modcon=system;;
+      esac;
+    fi;
+    if is_mounted $modtarget; then
+      mount -o rw,remount -t auto $modtarget && echo "$modtarget (rw)" >&2;
+    fi;
+    mkdir -p $(dirname $modtarget);
+    cp -rLf $module $modtarget;
+    chown 0:0 $modtarget;
+    chmod 644 $modtarget;
+    if [ "$modcon" ]; then
+      /system/bin/chcon "u:object_r:${modcon}_file:s0" $modtarget;
+    fi;
+    if is_mounted $modtarget; then
+      mount -o ro,remount -t auto $modtarget && echo "$modtarget (ro)" >&2;
+    fi;
+  done;
+  if [ ! -d /postinstall/tmp ]; then
+    for mount in /system /vendor /product; do
+      if is_mounted $mount; then
+        mount -o ro,remount -t auto $mount && echo "$mount (ro)" >&2;
+      fi;
+    done;
+  fi;
+
   cd $AKHOME;
 }
 
@@ -541,17 +545,28 @@ export PATH="$AKHOME/tools:$AKHOME/bin:$PATH";
 
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " " " ";
+  ui_print " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
-ui_print "$KERNEL_STRING";
+KERNEL_REVISION="$(file_getprop anykernel.sh kernel.revision)";
+KERNEL_MADE="$(file_getprop anykernel.sh kernel.made)";
+ANYKERNEL3_MADE="$(file_getprop anykernel.sh anykernel3.made)";
+KERNEL_COMPILER="$(file_getprop anykernel.sh kernel.compiler)";
+DEVICE_NAME="$(getprop ro.product.device)";
+MESSAGE_WORD="$(file_getprop anykernel.sh message.word)";
+ui_print "-- Kernel Revision      : $KERNEL_REVISION";
+ui_print "-- Kernel Developer     : $KERNEL_MADE";
+ui_print "-- AnyKernel3 Developer : $ANYKERNEL3_MADE";
+ui_print "-- Compiler             : $KERNEL_COMPILER";
+ui_print "-- Device               : $DEVICE_NAME";
+ui_print "_________________________________________________" " ";
 if [ -f version ]; then
   ui_print " ";
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " ";
+ui_print "- Preparing environmemt...";
 grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
 ui_print " ";
 
@@ -562,7 +577,8 @@ do_versioncheck;
 do_levelcheck;
 do_vendorlevelcheck;
 
-ui_print "Installing...";
+ui_print " ";
+ui_print "Flashing $KERNEL_STRING...";
 # hack to maintain support for anykernel.sh files that weren't updated correctly along with the AK core
 CORE=$(grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
@@ -581,6 +597,8 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " "Done!";
+ui_print "- Done!";
+ui_print " " "_________________________________________________";
+ui_print " " "$MESSAGE_WORD" "_________________________________________________" " ";
 export PATH="$OLD_PATH";
 unset OLD_PATH OUTFD ZIPFILE;
